import { SessionProvider } from 'components/SessionProvider'
import SideBar from 'components/SideBar'
import Login from 'components/Login'
import { getServerSession } from 'next-auth'
import '../styles/globals.css'
import { authOptions } from '../pages/api/auth/[...nextauth]'
import ClientProvider from 'components/ClientProvider'

export const metadata = {
  title: 'Jon\'s ChatGPT Messenger',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // NOTE THE USE OF await HERE, BECAUSE WE ARE USING getServerSession, WHICH IS AN ASYNC FUNCTION
  const session = await getServerSession(authOptions)

  console.log('session', session)

  return (
    <html lang="en">
      <head />
      <body>
        {/* SO TO GET THE session to pass into the provider, we import getServerSession from next-auth */}
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
          <div className="flex">

            {/* <SideBar /> */}
            <div className="bg-[#202202] max-w-xs h-screen md:min-w-[20rem]">
              <SideBar />
            </div>
            {/* Client Provider - Notifications */}
            <ClientProvider />

            <div className="bg-[#263238] flex-1">{children}</div>
          </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
