import '@/styles/globals.css'

export const metadata = {
  title: 'Jon\'s ChatGPT Messenger',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">

          {/* SideBar */}

          {/* Client Provider - Notifications */}
          <div className="bg-[#263238]">
            {children}
          </div>

        </div>
      </body>
    </html>
  )
}
