import '@/styles/globals.css'
import SideBar from 'components/SideBar'

export const metadata = {
  title: 'Jon\'s ChatGPT Messenger',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <div className="flex">

                      {/* <SideBar /> */}
          <div className="bg-[#202202] max-w-xs h-screen md:min-w-[20rem]"
          >
            <SideBar />
          </div>
          {/* Client Provider - Notifications */}
          <div className="bg-[#263238] flex-1">{children}</div>

        </div>
      </body>
    </html>
  )
}
